In [1]:
from sklearn.linear_model import LinearRegression
from pandas import read_csv

In [6]:
df = read_csv('Final.csv',header=0)
array=df.values
vol=array[:,2].reshape(-1, 1)
z=array[:,1]
reg = LinearRegression().fit(vol,z)
print(reg.score(vol,z))
reg.coef_

0.2596333124400525


array([0.00398088])

In [9]:
add=array[:,3].reshape(-1, 1)
reg = LinearRegression().fit(add,z)
print(reg.score(add,z))
reg.coef_

0.4297008243945307


array([0.016038])

In [10]:
trn=array[:,4].reshape(-1, 1)
reg = LinearRegression().fit(trn,z)
print(reg.score(trn,z))
reg.coef_

0.08395283328219061


array([0.01774032])

In [11]:
diff=array[:,5].reshape(-1, 1)
reg = LinearRegression().fit(diff,z)
print(reg.score(diff,z))
reg.coef_

0.30676234735478447


array([8.70800644e-10])

In [12]:
minimun=array[:,6].reshape(-1, 1)
reg = LinearRegression().fit(minimun,z)
print(reg.score(minimun,z))
reg.coef_

0.004418302668514507


array([-229.07656715])

In [13]:
blocksize=array[:,7].reshape(-1, 1)
reg = LinearRegression().fit(blocksize,z)
print(reg.score(blocksize,z))
reg.coef_

0.028797700932873593


array([0.00393704])

In [14]:
lite=array[:,8].reshape(-1, 1)
reg = LinearRegression().fit(lite,z)
print(reg.score(lite,z))
reg.coef_

0.8819935318540447


array([57.36293453])

In [15]:
gold=array[:,9].reshape(-1, 1)
reg = LinearRegression().fit(gold,z)
print(reg.score(gold,z))
reg.coef_

0.17591953228503465


array([20.98465592])

In [16]:
oil=array[:,10].reshape(-1, 1)
reg = LinearRegression().fit(oil,z)
print(reg.score(oil,z))
reg.coef_

0.47520433628058434


array([255.79065214])

In [17]:
exg=array[:,11].reshape(-1, 1)
reg = LinearRegression().fit(exg,z)
print(reg.score(exg,z))
reg.coef_

0.5969305554373219


array([61742.75665895])

In [18]:
wiki=array[:,12].reshape(-1, 1)
reg = LinearRegression().fit(wiki,z)
print(reg.score(wiki,z))
reg.coef_

0.3707316277192825


array([0.08024919])

In [19]:
twt=array[:,13].reshape(-1, 1)
reg = LinearRegression().fit(twt,z)
print(reg.score(twt,z))
reg.coef_

0.5177549317755854


array([0.13224776])

In [21]:
three_moving_average=array[:,14].reshape(-1, 1)
reg = LinearRegression().fit(three_moving_average,z)
print(reg.score(three_moving_average,z))
reg.coef_

0.9865307991186117


array([1.04270012])

In [22]:
nine_moving_average=array[:,15].reshape(-1, 1)
reg = LinearRegression().fit(nine_moving_average,z)
print(reg.score(nine_moving_average,z))
reg.coef_

0.9780683421205498


array([0.99225039])

In [23]:
four_moving_average=array[:,16].reshape(-1, 1)
reg = LinearRegression().fit(four_moving_average,z)
print(reg.score(four_moving_average,z))
reg.coef_

0.9658628265591321


array([0.98806535])

In [25]:
wsj=array[:,17].reshape(-1, 1)
reg = LinearRegression().fit(wsj,z)
print(reg.score(wsj,z))
reg.coef_

0.009419982915337966


array([718.59066798])

In [26]:
laws=array[:,18].reshape(-1, 1)
reg = LinearRegression().fit(laws,z)
print(reg.score(laws,z))
reg.coef_

0.09541050753215485


array([1511.68693897])

In [27]:
privacy=array[:,19].reshape(-1, 1)
reg = LinearRegression().fit(privacy,z)
print(reg.score(privacy,z))
reg.coef_

0.0007989627087746642


array([-133.4329325])

In [8]:
df = read_csv('data output2.csv',header=0)
array=df.values
sentiment=array[:,18].reshape(-1, 1)
z=array[:,2]
reg = LinearRegression().fit(vol,z)
print(reg.score(sentiment,z))
reg.coef_

0.0003532256730999217


array([139.05656782])