In [2]:
import statsmodels.api as sm
import pandas 
from pandas import read_csv
from pandas import DataFrame 
from sklearn import linear_model
from sklearn import preprocessing 

In [2]:
df = read_csv('data output.csv',header=0)
array=df.values
x=array[:,2:15]
y=array[:,1]
x=preprocessing.scale(x)
reg= linear_model.LinearRegression()
reg.fit(x,y)
print('Intercept: \n', reg.intercept_)
print('Coefficients: \n', reg.coef_)

Intercept: 
 3515.78504797048
Coefficients: 
 [-177.26306978   94.3618368   111.74022644  323.48763852   29.76638538
 -106.24006863  679.79299188  -33.72194756   56.7513236    76.43104906
  399.17100564   65.24188446 2639.31816322]


/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:180: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


In [3]:
x=sm.add_constant(x)
x=preprocessing.scale(x)
x=x.astype(float)
y=y.astype(float)
model = sm.OLS(y,x).fit()
summary=model.summary()
print(summary)

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.529
Model:                            OLS   Adj. R-squared:                  0.524
Method:                 Least Squares   F-statistic:                     115.7
Date:                Sun, 14 Apr 2019   Prob (F-statistic):          3.01e-208
Time:                        12:09:49   Log-Likelihood:                -12995.
No. Observations:                1355   AIC:                         2.602e+04
Df Residuals:                    1342   BIC:                         2.608e+04
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const               0          0        nan        n

/anaconda3/lib/python3.7/site-packages/statsmodels/regression/linear_model.py:1633: RuntimeWarning: divide by zero encountered in double_scalars
  return np.sqrt(eigvals[0]/eigvals[-1])
/anaconda3/lib/python3.7/site-packages/statsmodels/base/model.py:1100: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:877: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:877: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:1831: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)


In [7]:
df = read_csv('Final.csv',header=0)
array=df.values
x=array[:,2:21]
y=array[:,1]
print(x)
x=preprocessing.scale(x)
reg= linear_model.LinearRegression()
reg.fit(x,y)
print('Intercept: \n', reg.intercept_)
print('Coefficients: \n', reg.coef_)

[[103669.7 267891 143977 ... -0.54 -0.97 -0.97]
 [83719.46 276497 141999 ... -0.54 -0.97 -0.97]
 [74467.14 267584 129558 ... -0.54 -0.97 -0.97]
 ...
 [2674052.82 654299 299774 ... -0.86 1.0 0.95]
 [2382787.35 643452 296817 ... -0.78 1.0 0.95]
 [2456163.6 545186 262104 ... -0.78 1.0 0.95]]
Intercept: 
 3520.7670479704793
Coefficients: 
 [-1.27335326e+02  8.44625000e+01 -1.41645830e+00  3.12432180e+02
 -5.35219625e+00 -1.67391656e+01  4.81202560e+02  1.52716847e+01
  1.41919299e+01  3.50000795e+01  3.27035158e+02  7.07849457e+01
  2.88212714e+03  2.52667341e+02 -2.86158969e+02 -1.28187425e+01
  2.08145270e+01 -4.03331594e+01]


/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:180: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


In [8]:
'''
result reveals x1,x4,x7,x11,x13,x14 and x15 are closely linked to bitcoin price
x1: volume x4: mining difficulty, x7:litecoin price 
x13: 3 days moving average
x14: 9 days moving average
x15: 15 days moving average

'''
x=sm.add_constant(x)
x=preprocessing.scale(x)
x=x.astype(float)
y=y.astype(float)
model = sm.OLS(y,x).fit()
summary=model.summary()
print(summary)

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.530
Model:                            OLS   Adj. R-squared:                  0.524
Method:                 Least Squares   F-statistic:                     83.86
Date:                Mon, 13 May 2019   Prob (F-statistic):          2.76e-204
Time:                        11:09:56   Log-Likelihood:                -12996.
No. Observations:                1355   AIC:                         2.603e+04
Df Residuals:                    1337   BIC:                         2.612e+04
Df Model:                          18                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const               0          0        nan        n

/anaconda3/lib/python3.7/site-packages/statsmodels/regression/linear_model.py:1633: RuntimeWarning: divide by zero encountered in double_scalars
  return np.sqrt(eigvals[0]/eigvals[-1])
/anaconda3/lib/python3.7/site-packages/statsmodels/base/model.py:1100: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:877: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:877: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:1831: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
